"""migrate

Revision ID: 8bf4d0bb3e4f
Revises: 
Create Date: 2022-05-23 17:05:31.118690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bf4d0bb3e4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('district', sa.Column('nameru', sa.String(), nullable=True))
    op.add_column('district', sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=3857, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.create_index('idx_district_geometry', 'district', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.add_column('province', sa.Column('nameru', sa.String(), nullable=True))
    op.add_column('province', sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=3857, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.create_index('idx_province_geometry', 'province', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'created_at')
    op.drop_index('idx_province_geometry', table_name='province', postgresql_using='gist', postgresql_ops={})
    op.drop_column('province', 'geometry')
    op.drop_column('province', 'nameru')
    op.drop_index('idx_district_geometry', table_name='district', postgresql_using='gist', postgresql_ops={})
    op.drop_column('district', 'geometry')
    op.drop_column('district', 'nameru')
    op.drop_table('permission')
    # ### end Alembic commands ###
